name: Node CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: buildJar
        path: target

  runCodeGuruCIWorkFlow:
  
    runs-on: ubuntu-latest
    needs: buildJar

    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: buildJar
      # Step 1: Checkout the repository and provide your AWS credentials
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Region to access CodeGuru 

      # Step 2: Add CodeGuru Reviewer Action
      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          build_path: target # build artifact(s) directory
          s3_bucket: codeguru-reviewer-cicd-test-bucket1  # S3 Bucket with "codeguru-reviewer-*" prefix

      # Step 3: Upload results into GitHub
      - name: Upload review result
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeguru-results.sarif.json
